module.exports = {
  endOfLine: "auto",
  bracketSameLine: false,
  embeddedLanguageFormatting: "auto",
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  jsxSingleQuote: false,
  proseWrap: "preserve",
  quoteProps: "consistent",
  requirePragma: false,
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  singleQuote: false,
  trailingComma: "all",
  arrowParens: "always",
  experimentalTernaries: true,
  bracketSpacing: true,
  semi: true,
  singleAttributePerLine: false,
  vueIndentScriptAndStyle: false,

  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-curly",
    "prettier-plugin-jsdoc",
    "prettier-plugin-packagejson",
  ],

  // Import sorting rules
  importOrder: [
    "^(react|next|solid|astro)$",
    "",
    "^(@builder-io|qwik)$",
    "",
    "^(vue|nuxt|angular|svelte)$",
    "",
    "<BUILTIN_MODULES>",
    "",
    "<TYPES>",
    "<TYPES>^[.]",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^(@api|@assets|@ui|@|~)(/.*)$",
    "",
    "^[.]",
    "",
    "^(?!.*[.]css$)[./].*$",
    ".css$",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderTypeScriptVersion: "5.0.0",
};
