module.exports = {
  endOfLine: 'auto',
  bracketSameLine: false,
  embeddedLanguageFormatting: 'auto',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: false,
  proseWrap: 'preserve',
  quoteProps: 'consistent',
  requirePragma: false,
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  singleQuote: false,
  trailingComma: 'all',
  arrowParens: 'always',
  experimentalTernaries: true,
  bracketSpacing: true,
  semi: true,
  singleAttributePerLine: false,
  vueIndentScriptAndStyle: false,
};
