module.exports = {
  "complexity": [2, 20],
  "consistent-return": 2,
  "constructor-super": 2,
  "curly": 2,
  "default-param-last": 2,
  "dot-notation": 2,
  "eqeqeq": 2,
  "for-direction": 2,
  "func-name-matching": 2,
  "getter-return": 2,
  "guard-for-in": 2,
  "new-parens": 2,
  "no-alert": 2,
  "no-array-constructor": 2,
  "no-async-promise-executor": 2,
  "no-bitwise": 2,
  "no-caller": 2,
  "no-case-declarations": 2,
  "no-class-assign": 2,
  "no-compare-neg-zero": 2,
  "no-cond-assign": 2,
  "no-confusing-arrow": 2,
  "no-console": 2,
  "no-const-assign": 2,
  "no-constructor-return": 2,
  "no-control-regex": 2,
  "no-debugger": 2,
  "no-delete-var": 2,
  "no-div-regex": 2,
  "no-dupe-args": 2,
  "no-dupe-class-members": 2,
  "no-dupe-else-if": 2,
  "no-dupe-keys": 2,
  "no-duplicate-case": 2,
  "no-empty": 2,
  "no-empty-character-class": 2,
  "no-empty-pattern": 2,
  "no-eq-null": 2,
  "no-eval": 2,
  "no-ex-assign": 2,
  "no-extend-native": 2,
  "no-extra-bind": 2,
  "no-extra-boolean-cast": 2,
  "no-extra-label": 2,
  "no-extra-parens": 2,
  "no-extra-semi": 2,
  "no-fallthrough": 2,
  "no-floating-decimal": 2,
  "no-func-assign": 2,
  "no-global-assign": 2,
  "no-implicit-coercion": 2,
  "no-implicit-globals": 2,
  "no-implied-eval": 2,
  "no-import-assign": 2,
  "no-inline-comments": 2,
  "no-inner-declarations": 2,
  "no-invalid-regexp": 2,
  "no-irregular-whitespace": 2,
  "no-iterator": 2,
  "no-label-var": 2,
  "no-labels": 2,
  "no-lone-blocks": 2,
  "no-lonely-if": 2,
  "no-loop-func": 2,
  "no-loss-of-precision": 2,
  "no-misleading-character-class": 2,
  "no-mixed-spaces-and-tabs": 2,
  "no-multi-assign": 2,
  "no-multi-spaces": 2,
  "no-multi-str": 2,
  "no-negated-condition": 2,
  "no-new": 2,
  "no-new-func": 2,
  "no-new-object": 2,
  "no-new-symbol": 2,
  "no-new-wrappers": 2,
  "no-nonoctal-decimal-escape": 2,
  "no-obj-calls": 2,
  "no-octal": 2,
  "no-octal-escape": 2,
  "no-param-reassign": [
    2,
    {
      props: false,
    },
  ],
  "no-promise-executor-return": 2,
  "no-proto": 2,
  "no-prototype-builtins": 2,
  "no-redeclare": [
    2,
    {
      builtinGlobals: true,
    },
  ],
  "no-regex-spaces": 2,
  "no-restricted-exports": 0,
  "no-restricted-globals": 0,
  "no-restricted-imports": 0,
  "no-restricted-properties": 0,
  "no-restricted-syntax": 0,
  "no-return-assign": 2,
  "no-script-url": 2,
  "no-self-assign": 2,
  "no-self-compare": 2,
  "no-sequences": 2,
  "no-setter-return": 2,
  "no-shadow": [
    2,
    {
      builtinGlobals: false,
      hoist: "all",
    },
  ],
  "no-shadow-restricted-names": 2,
  "no-sparse-arrays": 2,
  "no-tabs": 2,
  "no-template-curly-in-string": 2,
  "no-ternary": 0,
  "no-this-before-super": 2,
  "no-throw-literal": 2,
  "no-trailing-spaces": 2,
  "no-undef": 2,
  "no-undef-init": 2,
  "no-undefined": 0,
  "no-underscore-dangle": 0,
  "no-unexpected-multiline": 2,
  "no-unmodified-loop-condition": 2,
  "no-unneeded-ternary": 2,
  "no-unreachable": 0,
  "no-unreachable-loop": 2,
  "no-unsafe-finally": 2,
  "no-unsafe-negation": 2,
  "no-unsafe-optional-chaining": 2,
  "no-unused-expressions": 2,
  "no-unused-labels": 2,
  "no-unused-private-class-members": 0,
  "no-unused-vars": 2,
  "no-use-before-define": [
    2,
    {
      classes: true,
      functions: false,
      variables: true,
    },
  ],
  "no-useless-backreference": 2,
  "no-useless-call": 2,
  "no-useless-catch": 2,
  "no-useless-computed-key": 2,
  "no-useless-concat": 2,
  "no-useless-constructor": 2,
  "no-useless-escape": 2,
  "no-useless-rename": [
    2,
    {
      ignoreDestructuring: false,
      ignoreExport: false,
      ignoreImport: false,
    },
  ],
  "no-useless-return": 2,
  "no-var": 2,
  "no-void": [
    2,
    {
      allowAsStatement: true,
    },
  ],
  "no-warning-comments": [
    1,
    {
      location: "start",
      terms: ["todo", "@toto"],
    },
  ],
  "no-whitespace-before-property": 2,
  "no-with": 2,
  "nonblock-statement-body-position": [2, "below"],
  "object-curly-newline": [
    2,
    {
      ExportDeclaration: "always",
      ImportDeclaration: "always",
      ObjectExpression: {
        minProperties: 1,
        multiline: true,
      },
      ObjectPattern: {
        minProperties: 1,
        multiline: true,
      },
    },
  ],
  "object-curly-spacing": 0,
  "object-property-newline": [
    2,
    {
      allowAllPropertiesOnSameLine: false,
    },
  ],
  "object-shorthand": [2, "always"],
  "one-var": [2, "never"],
  "one-var-declaration-per-line": 2,
  "operator-assignment": [2, "always"],
  "operator-linebreak": [2, "after"],
  "padded-blocks": [2, "never"],
  "padding-line-between-statements": [
    2,
    {
      blankLine: "always",
      next: "*",
      prev: "multiline-block-like",
    },
  ],
  "prefer-arrow-callback": 2,
  "prefer-const": 2,
  "prefer-destructuring": 0,
  "prefer-exponentiation-operator": 2,
  "prefer-named-capture-group": 0,
  "prefer-numeric-literals": 2,
  "prefer-object-spread": 2,
  "prefer-promise-reject-errors": 2,
  "prefer-regex-literals": [
    2,
    {
      disallowRedundantWrapping: true,
    },
  ],
  "prefer-rest-params": 2,
  "prefer-spread": 2,
  "prefer-template": 0,
  "promise/param-names": 2,
  "promise/prefer-await-to-callbacks": 0,
  "promise/prefer-await-to-then": 2,
  "promise/valid-params": 2,
  "quote-props": [
    2,
    "as-needed",
    {
      numbers: true,
    },
  ],
  "quotes": [2, "single"],
  "radix": 2,
  "require-atomic-updates": 2,
  "require-await": 0,
  "require-unicode-regexp": 2,
  "require-yield": 2,
  "rest-spread-spacing": [2, "never"],
  "semi": [2, "always"],
  "semi-spacing": [
    2,
    {
      after: true,
      before: false,
    },
  ],
  "semi-style": [2, "last"],
  "simple-import-sort/exports": 2,
  "simple-import-sort/imports": [2, { groups: [] }],
  "sort-imports": 0,
  "sort-keys": 0,
  "sort-vars": 2,
  "space-before-blocks": [2, "always"],
  "space-before-function-paren": [2, "always"],
  "space-in-parens": [2, "never"],
  "space-infix-ops": 2,
  "space-unary-ops": [
    2,
    {
      nonwords: false,
      words: true,
    },
  ],
  "spaced-comment": [2, "always"],
  "strict": [2, "never"],
  "switch-colon-spacing": [
    2,
    {
      after: true,
      before: false,
    },
  ],
  "symbol-description": 2,
  "template-curly-spacing": [2, "never"],
  "template-tag-spacing": [2, "never"],
  "unicode-bom": [2, "never"],
  "use-isnan": 2,
  "valid-typeof": [
    2,
    {
      requireStringLiterals: true,
    },
  ],
  "vars-on-top": 2,
  "wrap-iife": [2, "inside"],
  "wrap-regex": 0,
  "yield-star-spacing": [
    2,
    {
      after: true,
      before: false,
    },
  ],
  "yoda": [2, "never"],
};
