const config = require('../config');

module.exports = {
  'array-callback-return': config.WARN,
  'getter-return': config.WARN,
  'new-parens': config.WARN,
  'no-array-constructor': config.WARN,
  'no-caller': config.ERROR,
  'no-cond-assign': [config.WARN, 'except-parens'],
  'no-constant-condition': config.ERROR,
  'no-unreachable': config.ERROR,
  'no-constant-binary-expression': config.ERROR,
  'no-sequences': config.ERROR,
  'no-const-assign': config.ERROR,
  'no-control-regex': config.WARN,
  'no-dupe-args': config.WARN,
  'no-dupe-class-members': config.WARN,
  'no-dupe-keys': config.WARN,
  'no-duplicate-case': config.WARN,
  'no-empty-character-class': config.WARN,
  'no-empty-pattern': config.WARN,
  'no-duplicate-imports': config.WARN,
  'no-empty': [config.WARN, { allowEmptyCatch: true }],
  'no-eval': config.ERROR,
  'no-ex-assign': config.WARN,
  'no-extend-native': config.WARN,
  'no-extra-bind': config.WARN,
  'no-extra-label': config.WARN,
  'no-extra-boolean-cast': config.WARN,
  'no-func-assign': config.ERROR,
  'no-global-assign': config.ERROR,
  'no-implied-eval': config.WARN,
  'no-invalid-regexp': config.ERROR,
  'no-label-var': config.ERROR,
  'no-labels': [config.WARN, { allowLoop: true, allowSwitch: false }],
  'no-lone-blocks': config.WARN,
  'no-loop-func': config.WARN,
  'no-mixed-operators': [
    config.WARN,
    {
      groups: [
        ['&', '|', '^', '~', '<<', '>>', '>>>'],
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
      allowSamePrecedence: false,
    },
  ],
  'no-unsafe-negation': config.ERROR,
  'no-new-func': config.WARN,
  'no-new-object': config.WARN,
  'no-octal': config.WARN,
  'no-redeclare': config.ERROR,
  'no-restricted-imports': [config.WARN],
  'no-script-url': config.WARN,
  'no-self-assign': config.WARN,
  'no-self-compare': config.WARN,
  'no-shadow-restricted-names': config.WARN,
  'no-sparse-arrays': config.WARN,
  'no-template-curly-in-string': config.WARN,
  'no-this-before-super': config.WARN,
  'no-undef': config.ERROR,
  'no-unused-expressions': [
    config.ERROR,
    {
      allowShortCircuit: true,
      allowTernary: true,
      allowTaggedTemplates: true,
    },
  ],
  'no-unused-labels': config.WARN,
  'no-unused-vars': [
    config.WARN,
    {
      args: 'none',
      ignoreRestSiblings: true,
      argsIgnorePattern: '^_',
    },
  ],
  'no-use-before-define': [config.ERROR, { classes: false, functions: false, variables: false }],
  'no-useless-computed-key': config.ERROR,
  'no-useless-concat': config.ERROR,
  'no-useless-constructor': config.ERROR,
  'no-useless-escape': config.ERROR,
  'no-useless-rename': [
    config.WARN,
    {
      ignoreDestructuring: false,
      ignoreImport: false,
      ignoreExport: false,
    },
  ],
  'require-yield': config.WARN,
  'use-isnan': config.WARN,
  'valid-typeof': config.WARN,
};
