const config = require("./config");

module.exports = {
  extends: ["./index.js", "plugin:jsx-a11y/strict"],
  plugins: ["jsx-a11y"],
  rules: {
    "jsx-a11y/alt-text": config.ERROR,
    "jsx-a11y/anchor-has-content": config.ERROR,
    "jsx-a11y/anchor-is-valid": config.ERROR,
    "jsx-a11y/aria-activedescendant-has-tabindex": config.ERROR,
    "jsx-a11y/aria-props": config.ERROR,
    "jsx-a11y/aria-proptypes": config.ERROR,
    "jsx-a11y/aria-role": config.ERROR,
    "jsx-a11y/aria-unsupported-elements": config.ERROR,
    "jsx-a11y/autocomplete-valid": config.ERROR,
    "jsx-a11y/click-events-have-key-events": config.ERROR,
    "jsx-a11y/control-has-associated-label": config.OFF,
    "jsx-a11y/heading-has-content": config.ERROR,
    "jsx-a11y/html-has-lang": config.ERROR,
    "jsx-a11y/iframe-has-title": config.ERROR,
    "jsx-a11y/img-redundant-alt": config.ERROR,
    "jsx-a11y/interactive-supports-focus": [
      config.ERROR,
      {
        tabbable: [
          "button",
          "checkbox",
          "link",
          "searchbox",
          "spinbutton",
          "switch",
          "textbox",
        ],
      },
    ],
    "jsx-a11y/label-has-associated-control": config.ERROR,
    "jsx-a11y/lang": config.OFF,
    "jsx-a11y/media-has-caption": config.ERROR,
    "jsx-a11y/mouse-events-have-key-events": config.ERROR,
    "jsx-a11y/no-access-key": config.ERROR,
    "jsx-a11y/no-autofocus": config.OFF,
    "jsx-a11y/no-distracting-elements": config.ERROR,
    "jsx-a11y/no-interactive-element-to-noninteractive-role": [
      config.ERROR,
      {
        canvas: ["img"],
        tr: ["none", "presentation"],
      },
    ],
    "jsx-a11y/no-noninteractive-element-interactions": [
      config.ERROR,
      {
        alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
        body: ["onError", "onLoad"],
        dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
        handlers: [
          "onClick",
          "onError",
          "onLoad",
          "onMouseDown",
          "onMouseUp",
          "onKeyPress",
          "onKeyDown",
          "onKeyUp",
        ],
        iframe: ["onError", "onLoad"],
        img: ["onError", "onLoad"],
      },
    ],
    "jsx-a11y/no-noninteractive-element-to-interactive-role": [
      config.ERROR,
      {
        fieldset: ["radiogroup", "presentation"],
        li: ["menuitem", "option", "row", "tab", "treeitem"],
        ol: [
          "listbox",
          "menu",
          "menubar",
          "radiogroup",
          "tablist",
          "tree",
          "treegrid",
        ],
        table: ["grid"],
        td: ["gridcell"],
        ul: [
          "listbox",
          "menu",
          "menubar",
          "radiogroup",
          "tablist",
          "tree",
          "treegrid",
        ],
      },
    ],
    "jsx-a11y/no-noninteractive-tabindex": [
      config.ERROR,
      {
        allowExpressionValues: true,
        roles: ["tabpanel"],
        tags: [],
      },
    ],
    "jsx-a11y/no-redundant-roles": config.ERROR,
    "jsx-a11y/no-static-element-interactions": [
      config.ERROR,
      {
        allowExpressionValues: true,
        handlers: [
          "onClick",
          "onMouseDown",
          "onMouseUp",
          "onKeyPress",
          "onKeyDown",
          "onKeyUp",
        ],
      },
    ],
    "jsx-a11y/role-has-required-aria-props": config.ERROR,
    "jsx-a11y/role-supports-aria-props": config.ERROR,
    "jsx-a11y/scope": config.ERROR,
    "jsx-a11y/tabindex-no-positive": config.ERROR,
  },
};
